python train.py --data ./dataset/names2.txt \
                --seq_len 32 \
                --d_model 512 \
                --ff_dim 1024 \
                --n_head 4 \
                --n_block 3 \
                --gpu 0 \
                --batch 8 \
                --lr 3e-4 \
                --epoch 10 \
                --ckpt ./model/model-hispanic.pth